<%@ taglib uri="http://java.sun.com/jsp/jstl/core" prefix="c"%>
<%--
	On this page we list all the deposits for a particular goal as well as the Total for all of the deposits.
	
	Model:
	- List<Deposit> getDepositsByGoal(Int goalId);
	- Int goalID is the numeric goal number automatically incremented when a new goal is added
	- String goal  if the page is filtered to a specific goal, this will
	                   be the name of that goal. Otherwise it will not be
	                   defined.
 --%>

<html>
<head>
<%--<%@ "autogenerated --><meta http-equiv="Content-Type" content="text/html; charset=ISO-8859-1">
<title>Insert title here</title>--%>

<%@ include file="head.jsp"%>
</head>
<body>
	<div class="nav">
		<a href="<c:url value="/"/>">Home</a>
	</div>

	<div>
		<table>
			<tr>
				<th>Deposit</th>
			</tr>
			<c:forEach var="deposit" items="${deposits}">
				<tr>
					<td><a href="<c:url value="/deposits/${deposit.depositId}"/>">
						<c:out value="${ deposit.depositAmount }" /></a></td>
						
					<td><c:out value="${ deposit.depositAmount }" /> 
						<a href="<c:url value="/deposits?goal=${deposit.goalId}"/>">(filter)</a></td>
					
					<td><c:out value="${ deposit.currentDate }" /> 
						<a href="<c:url value="/deposits?date=${deposit.currentDate}"/>">(filter)</a></td>
						
					<td><c:out value="${ deposit.goalId }" /></td>
					
					<td><c:if test="${ deposit.blackAndWhite }">&#10004; 	
					</c:if></td>
					
					<td><c:out value="${ deposit.origin }" /></td>

				</tr>
			</c:forEach>
		</table>
	</div>

<%--	<div>
		<ul>
			<li>Deposit 1:</li>
			<li>Deposit 2:</li>
			<li>Deposit 3:</li>
		</ul>
	</div> --%>

	<div>
		<h2>Total Deposits</h2>
		<c:out value="${depositAmount}"/>
	</div>

	<form method="post">
		<div>
			<label>Deposit Amount:</label> <input type="text"
				name="depositAmount" value="${depositDao.depositAmount}" />
		</div>
			
		<button type="submit">Submit</button>
	</form>
	

</body>
</html>
